apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-helper-deployment
spec:
  selector:
    matchLabels:
      app: flask-helper
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-helper
    spec:
      containers:
      - name: flask
        #TODO : FIXME
        image:  rg.fr-par.scw.cloud/registry-discovery/flask-helper
        ports:
          - containerPort: 5000
        #TODO : FIXME
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-release-redis
              key: redis-password
        - name: REDIS_HOST
          value: "my-release-redis-master"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-helper-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: flask-helper
