---
- name: Deploy K3S and Rancher
  hosts: "{{ workspace | default ( lookup('env', 'KUBEFACTORY_WORKSPACE') ) }}"
  become: yes
  gather_facts: yes
  strategy: linear
  tags:
    - system

  roles:
    - role: "rtnp.galaxie_clans.rproxy"
      vars:
        rproxy_nginx_enable_sites: no

    - role: "k3s"
    - role: "rancher"

    - role: "rtnp.galaxie_clans.rproxy"
      vars:
        rproxy_nginx_enable_sites: yes
